In [1]:
import pandas as pd
df=pd.read_csv("C:\\Users\\saipr\\Email_Categorisation\\full_dataset.csv")
df.head()

,id,subject,body,text,category,category_id
0,promotions_582,Anniversary Special: Buy one get one free,"As our loyal customer, get exclusive $60 off $...",Anniversary Special: Buy one get one free As o...,promotions,1
1,spam_1629,Your Amazon was used on new device,Your $5000 refund is processed. Claim: bit.ly/...,Your Amazon was used on new device Your $5000 ...,spam,3
2,spam_322,Re: Your Google inquiry,"Hi, following up about your Google application...","Re: Your Google inquiry Hi, following up about...",spam,3
3,social_media_80,Digital Ritual Experience Creation,Cross-cultural ceremony design. Join: virtualr...,Digital Ritual Experience Creation Cross-cultu...,social_media,2
4,forum_1351,"Your post was moved to ""Programming Help""","Trending: ""cooking"" (258 comments). View: supp...","Your post was moved to ""Programming Help"" Tren...",forum,0

In [2]:
df['category'].value_counts()

category
verify_code     2251
forum           2250
social_media    2245
promotions      2245
spam            2243
updates         2243
Name: count, dtype: int64

In [3]:
df[df['category']=='updates']

,id,subject,body,text,category,category_id
21,updates_1347,Policy update: Terms of Service changes,Restaurant Main pool closed Aug 20-22 for main...,Policy update: Terms of Service changes Restau...,updates,4
26,updates_578,"Your appointment confirmed: Dec 20, 3-5AM GMT",Thank you! $156.50 payment applied to account....,"Your appointment confirmed: Dec 20, 3-5AM GMT ...",updates,4
32,updates_1570,Payment received: Invoice INV-7891,We've updated our Privacy Policy. Review chang...,Payment received: Invoice INV-7891 We've updat...,updates,4
36,updates_1751,Auto-payment failed for subscription,Your September statement is available. View/do...,Auto-payment failed for subscription Your Sept...,updates,4
43,updates_1588,Membership upgrade: delivered achieved!,We've updated our User Agreement. Review chang...,Membership upgrade: delivered achieved! We've ...,updates,4
...,...,...,...,...,...,...
13430,updates_1552,Security upgrade: password encryption enabled,Your July statement is available. View/downloa...,Security upgrade: password encryption enabled ...,updates,4
13443,updates_552,Security upgrade: 2FA enabled,Your August statement is available. View/downl...,Security upgrade: 2FA enabled Your August stat...,updates,4
13452,updates_870,Data usage alert: 90% of monthly quota,Your August statement is available. View/downl...,Data usage alert: 90% of monthly quota Your Au...,updates,4
13463,updates_9,Security upgrade: 2FA enabled,Two-factor authentication activated per your r...,Security upgrade: 2FA enabled Two-factor authe...,updates,4
13466,updates_1643,Membership upgrade: processing achieved!,Your September statement is available. View/do...,Membership upgrade: processing achieved! Your ...,updates,4

In [4]:
df

,id,subject,body,text,category,category_id
0,promotions_582,Anniversary Special: Buy one get one free,"As our loyal customer, get exclusive $60 off $...",Anniversary Special: Buy one get one free As o...,promotions,1
1,spam_1629,Your Amazon was used on new device,Your $5000 refund is processed. Claim: bit.ly/...,Your Amazon was used on new device Your $5000 ...,spam,3
2,spam_322,Re: Your Google inquiry,"Hi, following up about your Google application...","Re: Your Google inquiry Hi, following up about...",spam,3
3,social_media_80,Digital Ritual Experience Creation,Cross-cultural ceremony design. Join: virtualr...,Digital Ritual Experience Creation Cross-cultu...,social_media,2
4,forum_1351,"Your post was moved to ""Programming Help""","Trending: ""cooking"" (258 comments). View: supp...","Your post was moved to ""Programming Help"" Tren...",forum,0
...,...,...,...,...,...,...
13472,social_media_817,News from groups you follow,"Alex: ""Anyone free this weekend?"" Lisa: ""Count...","News from groups you follow Alex: ""Anyone free...",social_media,2
13473,verify_code_368,Identity verification required: 756179,Your access code is 907472 for transaction aut...,Identity verification required: 756179 Your ac...,verify_code,5
13474,forum_898,Moderation notice: Community Guidelines update,"Trending: ""cooking"" (258 comments). View: supp...",Moderation notice: Community Guidelines update...,forum,0
13475,spam_2152,Renew Google subscription 80% off,Your package couldn't be delivered. Tracking# ...,Renew Google subscription 80% off Your package...,spam,3
13476,promotions_1900,Early access: Summer sale start now,Final hours of biggest sale. Up to 30% off: ex...,Early access: Summer sale start now Final hour...,promotions,1

In [5]:
df.drop(['id','subject','body','category_id'],axis=1,inplace=True)

In [6]:

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Features and target
X = df["text"]
y = df["category"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [7]:
# Create TF-IDF vectorizer
tfidf = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    max_features=10000,
    ngram_range=(1, 2)
)

# Learn vocabulary and transform training data
X_train_tfidf = tfidf.fit_transform(X_train)

# Transform test data
X_test_tfidf = tfidf.transform(X_test)

# Create Logistic Regression model
lr_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

# Train the model
lr_model.fit(X_train_tfidf, y_train)

# Predict
y_pred = lr_model.predict(X_test_tfidf)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9933234421364985

Classification Report:

              precision    recall  f1-score   support

       forum       0.99      0.99      0.99       450
  promotions       1.00      0.98      0.99       449
social_media       1.00      0.99      0.99       449
        spam       0.99      1.00      1.00       449
     updates       0.99      1.00      0.99       449
 verify_code       0.99      1.00      1.00       450

    accuracy                           0.99      2696
   macro avg       0.99      0.99      0.99      2696
weighted avg       0.99      0.99      0.99      2696


Confusion Matrix:

[[447   0   1   0   1   1]
 [  1 442   1   0   4   1]
 [  1   0 444   3   0   1]
 [  0   0   0 449   0   0]
 [  2   0   0   0 447   0]
 [  0   0   0   1   0 449]]

In [8]:
X_train_tfidf[0]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 24 stored elements and shape (1, 10000)>

In [9]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Features and target
X = df["text"]
y = df["category"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

# Create pipeline
model = Pipeline([
    ("tfidf", TfidfVectorizer(
        lowercase=True,
        stop_words="english",
        max_features=10000,
        ngram_range=(1, 2)
    )),
    ("clf", LogisticRegression(
        max_iter=1000,
        random_state=42
    ))
])

# Train
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9913452027695351

Classification Report:

              precision    recall  f1-score   support

       forum       0.99      0.99      0.99       675
  promotions       1.00      0.99      0.99       674
social_media       0.99      0.99      0.99       674
        spam       0.99      0.99      0.99       673
     updates       0.99      0.99      0.99       673
 verify_code       0.99      1.00      0.99       675

    accuracy                           0.99      4044
   macro avg       0.99      0.99      0.99      4044
weighted avg       0.99      0.99      0.99      4044


Confusion Matrix:

[[669   0   4   0   1   1]
 [  1 665   2   0   5   1]
 [  1   0 669   3   0   1]
 [  1   0   0 668   2   2]
 [  5   0   2   0 664   2]
 [  0   0   0   1   0 674]]

In [10]:
clf = model.named_steps["clf"]

print(clf.coef_)

[[-0.1080528  -0.02210692 -0.05119907 ... -0.03393348 -0.07509296
  -0.07509296]
 [-0.10096777 -0.02309779 -0.03352066 ... -0.02321517 -0.07295096
  -0.07295096]
 [-0.08908854 -0.01460128 -0.03457956 ... -0.02857547 -0.07596195
  -0.07596195]
 [-0.14079428 -0.01579018 -0.03987359 ... -0.0280564   0.43507717
   0.43507717]
 [ 0.38215789  0.02997317  0.12374716 ...  0.15421063 -0.11454777
  -0.11454777]
 [ 0.05674549  0.04562299  0.03542572 ... -0.0404301  -0.09652352
  -0.09652352]]

In [11]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Features and target
X = df["text"]
y = df["category"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Create Pipeline
nb_model = Pipeline([
    ("tfidf", TfidfVectorizer(
        lowercase=True,
        stop_words="english",
        max_features=10000,
        ngram_range=(1, 2)
    )),
    ("clf", MultinomialNB(alpha=1.0))
])

# Train
nb_model.fit(X_train, y_train)

# Predict
y_pred = nb_model.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9844213649851632

Classification Report:

              precision    recall  f1-score   support

       forum       0.97      0.98      0.98       450
  promotions       1.00      0.98      0.99       449
social_media       1.00      0.98      0.99       449
        spam       0.98      0.99      0.98       449
     updates       0.98      0.98      0.98       449
 verify_code       0.98      0.99      0.99       450

    accuracy                           0.98      2696
   macro avg       0.98      0.98      0.98      2696
weighted avg       0.98      0.98      0.98      2696


Confusion Matrix:

[[443   0   0   1   5   1]
 [  2 440   0   2   3   2]
 [  3   0 441   4   0   1]
 [  2   0   1 445   1   0]
 [  5   0   1   2 438   3]
 [  0   0   0   1   2 447]]

In [12]:
X_train[0]

'Anniversary Special: Buy one get one free As our loyal customer, get exclusive $60 off $75+: example.com/6058 Offer code: WELCOME20.'

In [13]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

In [14]:
# Features and labels
X = df["text"].values
y = df["category"].values

# Encode labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [15]:
VOCAB_SIZE = 10000
MAX_LEN = 100

tokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token="<OOV>")

tokenizer.fit_on_texts(X_train)

train_sequences = tokenizer.texts_to_sequences(X_train)
test_sequences = tokenizer.texts_to_sequences(X_test)

X_train_pad = pad_sequences(
    train_sequences,
    maxlen=MAX_LEN,
    padding="post",
    truncating="post"
)

X_test_pad = pad_sequences(
    test_sequences,
    maxlen=MAX_LEN,
    padding="post",
    truncating="post"
)

In [16]:
len(X_train_pad[0])

100

In [17]:
model = Sequential([
    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=128,
        input_length=MAX_LEN
    ),

    SimpleRNN(64),

    Dense(32, activation="relu"),

    Dense(len(label_encoder.classes_), activation="softmax")
])

c:\Users\saipr\Email_Categorisation\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [18]:
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [19]:
history = model.fit(
    X_train_pad,
    y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/10
270/270 ━━━━━━━━━━━━━━━━━━━━ 7s 18ms/step - accuracy: 0.7973 - loss: 0.6559 - val_accuracy: 0.9550 - val_loss: 0.2351
Epoch 2/10
270/270 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - accuracy: 0.9627 - loss: 0.1834 - val_accuracy: 0.9476 - val_loss: 0.2598
Epoch 3/10
270/270 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.9761 - loss: 0.1251 - val_accuracy: 0.9254 - val_loss: 0.3815
Epoch 4/10
270/270 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.9563 - loss: 0.1794 - val_accuracy: 0.9597 - val_loss: 0.2043
Epoch 5/10
270/270 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.9404 - loss: 0.2246 - val_accuracy: 0.9147 - val_loss: 0.3901
Epoch 6/10
270/270 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.7477 - loss: 0.6998 - val_accuracy: 0.7339 - val_loss: 0.6930
Epoch 7/10
270/270 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.7556 - loss: 0.6430 - val_accuracy: 0.7867 - val_loss: 0.5874
Epoch 8/10
270/270 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - accuracy: 0.9416 - loss: 0.2550 - val_accuracy: 0.9420 - val_loss: 0.2952
Epoch 9/10
270/270 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.7645 - loss: 0.7954 - val_accuracy: 0.7710 - val_loss: 0.8410
Epoch 10/10
270/270 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.9180 - loss: 0.3304 - val_accuracy: 0.9281 - val_loss: 0.3516

In [20]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_pad)

y_pred = np.argmax(y_pred, axis=1)

print(classification_report(
    y_test,
    y_pred,
    target_names=label_encoder.classes_
))

85/85 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
              precision    recall  f1-score   support

       forum       0.96      0.87      0.91       450
  promotions       0.90      0.93      0.92       449
social_media       0.92      0.93      0.93       449
        spam       0.93      0.95      0.94       449
     updates       0.92      0.93      0.92       449
 verify_code       0.91      0.93      0.92       450

    accuracy                           0.92      2696
   macro avg       0.92      0.92      0.92      2696
weighted avg       0.92      0.92      0.92      2696

In [21]:
y_pred[0]

np.int64(1)

In [23]:
len(y)

13477

In [28]:
df['category'].value_counts()

category
verify_code     2251
forum           2250
social_media    2245
promotions      2245
spam            2243
updates         2243
Name: count, dtype: int64